package:
  name: hpnl
  version: 1.0

source:
  path: ../../../thirdparty/HPNL/

requirements:
  build:
    - gcc   [linux]
    - libgcc [linux]
    - cmake 3.11.*


about:
  home: https://github.com/Intel-bigdata/HPNL
  license: https://github.com/Intel-bigdata/HPNL/blob/master/LICENSE.txt
  license_file:
    - LICENSE.txt
  summary: HPNL is a light-weight network library built on Libfabric for big data application.

