package:
  name: hpnl
  version: 1.0

source:
  path: ../../../thirdparty/HPNL/

requirements:
  build:
    - gcc   [linux]
    - libgcc [linux]
    - cmake 3.11.*
    - libfabric 1.0
  run:
    - libfabric 1.0
