sudo: required
dist: trusty
language: java
jobs:
  include:
    #Other modules can refer to oap-cache-oap to build independent travis-ci job,
    #oap-cache-oap is a CI building demo of the corresponding module oap-cache/oap.
    - name: oap-cache-oap
      before_install:
#      - sudo apt-get update
      - sudo apt-get install libpthread-stubs0-dev
      - sudo apt-get install libnuma-dev
      - echo $TRAVIS_COMMIT_MESSAGE
      - sudo apt-get install cmake
      - cd ${TRAVIS_BUILD_DIR}/oap-cache/oap/dev
      - ./install_vmemcache.sh
      - ./install_arrow.sh
      - ./install_memkind.sh
      script:
      - cd ${TRAVIS_BUILD_DIR}
      - mvn clean -q -Ppersistent-memory -Pvmemcache test
    - name: oap-shuffle-remote-shuffle
      install:
      - #echo install step
      script:
      - cd ${TRAVIS_BUILD_DIR}/oap-shuffle/remote-shuffle
      - mvn -q test
