sudo: required
dist: trusty
language: java
before_install:
- sudo apt-get install cmake
- sudo apt-get install libpthread-stubs0-dev
- sudo apt-get install libnuma-dev
install:
- # Download spark 2.4.4
- "[ -f spark ] || mkdir spark && cd spark && wget http://archive.apache.org/dist/spark/spark-2.4.4/spark-2.4.4-bin-hadoop2.7.tgz && cd .."
- "tar -xf ./spark/spark-2.4.4-bin-hadoop2.7.tgz"
- "export SPARK_HOME=`pwd`/spark-2.4.4-bin-hadoop2.7"
before_script:
- cd /tmp
- git clone https://github.com/memkind/memkind.git
- cd memkind && ./build.sh
- make
- sudo make install
- cd ../
- git clone https://github.com/summerDG/spark-sql-perf.git
- cd spark-sql-perf
- mvn install:install-file -Dfile=./spark-sql-perf_2.11-0.4.11-SNAPSHOT.jar -DgroupId=com.databricks -DartifactId=spark-sql-perf_2.11 -Dversion=0.4.11-SNAPSHOT -Dpackaging=jar
- cd ${TRAVIS_BUILD_DIR}
script:
- mvn clean -q -Ppersistent-memory test


