sudo: required
dist: trusty
language: java
jobs:
  include:
    #Other modules can refer to oap-cache-oap to build independent travis-ci job,
    #oap-cache-oap is a CI building demo of the corresponding module oap-cache/oap.
    - name: oap-arrow-plasma
    before_install:
    - echo $TRAVIS_COMMIT_MESSAGE
    - sudo apt-get install cmake
    - #install numactl-devel
    - apt-get install numactl-devel libcurl-devel rpm-build
    before_script:
    - #install vemecache
    - git clone https://github.com/pmem/vmemcache.git
    - pushd vmemcache
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCPACK_GENERATOR=rpm
    - make package
    - sudo rpm -i libvmemcache*.rpm
    - popd
    - #install arrow and plasms
    - cd /tmp
    - git clone https://github.com/jikunshang/arrow-1.git
    - cd arrow-1 && git checkout rebase_oap_master
    - cd /cpp
    - rm -rf release
    - mkdir release
    - cd release
    script:
    - cd ${TRAVIS_BUILD_DIR}
    - cd cpp && mkdir build && cd build
    - cmake .. && make
    - name: oap-cache-oap
      before_install:
      - sudo apt-get install cmake
      - sudo apt-get install libpthread-stubs0-dev
      - sudo apt-get install libnuma-dev
      install:
      - # Download spark 2.4.4
      - "[ -f spark ] || mkdir spark && cd spark && wget http://archive.apache.org/dist/spark/spark-2.4.4/spark-2.4.4-bin-hadoop2.7.tgz && cd .."
      - "tar -xf ./spark/spark-2.4.4-bin-hadoop2.7.tgz"
      - "export SPARK_HOME=`pwd`/spark-2.4.4-bin-hadoop2.7"
      before_script:
      - cd /tmp
      - git clone https://github.com/memkind/memkind.git
      - cd memkind && ./build.sh
      - make
      - sudo make install
      - cd ${TRAVIS_BUILD_DIR}
      script:
      - cd ${TRAVIS_BUILD_DIR}
      - mvn clean -q -Ppersistent-memory test
    - name: oap-shuffle-remote-shuffle
      script:
      - cd ${TRAVIS_BUILD_DIR}/oap-shuffle/remote-shuffle/
      - mvn -q test
