package:
  name: vmemcache
  version: 1.0

source:
  path: ../../../thirdparty/vmemcache/

requirements:
  build:
    - gcc   [linux]
    - libgcc [linux]
    - cmake 3.11.*

about:
  home: https://software.intel.com/content/www/us/en/develop/tools.html
  license: Intel Simplified Software License
  license_file:
    - LICENSE.txt
    - tpp.txt
  summary: Summary description of package. Can include a url
  description: '
<strong>LEGAL NOTICE: Use of this software package is subject to the software license agreement (as set forth above, in the license section of the installed Conda package and/or the README file) and all notices, disclaimers or license terms for third party or open source software included in or with the software.</strong>
<br/><br/>
EULA: <a href="https://software.intel.com/content/dam/develop/external/us/en/documents/pdf/intel-simplified-software-license.pdf" target="_blank">Replace with license name and update link</a><br/>
Third Party Programs: hyperlink to repository TPP file
<br/><br/>
Optional detailed description. Can be multi-line and include markup.
'
  dev_url: hyperlink to open source repository
  doc_url: hyperlink to documentation