package:
  name: vmemcache
  version: 0.8

source:
  path: ../../../thirdparty/vmemcache/

requirements:
  build:
    - gcc   [linux]
    - libgcc [linux]
    - cmake 3.11.*

about:
  home: https://github.com/pmem/vmemcache
  license: Intel Simplified Software License
  license_file:
    - LICENSE
  summary: Libvmemcache is an embeddable and lightweight in-memory caching solution.

  dev_url: https://github.com/pmem/vmemcache.git
  doc_url: https://github.com/pmem/vmemcache.git