package:
  name: memkind
  version: 1.10.0

build:
  number: 0

source:
  path: ../../../thirdparty/memkind/

requirements:
  build:
    - gcc   4.8.5
    - autoconf
    - automake
    - libtool


about:
  home: https://github.com/Intel-bigdata/memkind
  license: https://github.com/Intel-bigdata/memkind/blob/v1.10.0-oap-0.7/COPYING
  license_file:
    - COPYING
  summary: The memkind library is a user extensible heap manager built on top of jemalloc which enables control of memory characteristics and a partitioning of the heap between kinds of memory.
