package:
  name: oap
  version: 0.1.0

build:
  number: 3

requirements:
  run:
    - vmemcache
    - memkind
    - intel-arrow-cpp
    - hpnl
about:
  summary: Optimized Analytics Packages for Spark is a project to optimize Spark by providing optimized implmentation of packages in various aspects including cache, shuffle, and so on.
