name: 'Arrow-cpp build'
on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 0 * * *
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: conda-incubator/setup-miniconda@v1
        with:
          miniconda-version: "latest"
          auto-activate-base: true

      - name: Set up JDK 1.8
        shell: bash -l {0}
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install -y openjdk-8-jdk

      - name: setup-environment
        shell: bash -l {0}
        run: |
          conda activate base
          conda info
          conda install -y anaconda-client conda-build
          echo "Y"|anaconda login  --username '${{ secrets.USR }}' --password '${{ secrets.PWD }}'
          conda list

      - name: clone-arrow
        shell: bash -l {0}
        env:
          ARROW_BRANCH: master
        run: |
          mkdir -p  dev/thirdparty
          cd dev/thirdparty
          git clone https://github.com/Intel-bigdata/arrow.git -b "$ARROW_BRANCH"

      - name: build-arrow
        shell: bash -l {0}
        run: |
          cd dev/conda-release/conda-recipes/arrow
          conda config --add channels intel
          conda config --add channels conda-forge
          conda config --set anaconda_upload yes
          conda build .